install apple-gcc42
install autoconf
install boot2docker
install brew-cask
install docker
install freetype
install go
install google-app-engine
install imagemagick
install jpeg
install libpng
install libtool
install node
install openssl
install pkg-config
install pyenv
install rbenv
install ruby-build
